version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./coursework:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - phpmyadmin
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./coursework:/var/www/html:delegated
  mysql:
    image: "mariadb:10.7.1"
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - maria_db:/var/lib/mysql
    depends_on:
      - php
  phpmyadmin:
    image: "phpmyadmin:latest"
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - "3306:80"
    depends_on:
      - mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./coursework:/var/www/html
volumes:
  maria_db:
    external: true
